version: '3.9'

services:
  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
  database:
    image: postgres
    container_name: db-rentx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=rentx
      - POSTGRES_USER=ale
      - POSTGRES_PASSWORD=ale
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
